import { AllTeams, Trophy, Achievement, Position, PlayerStats, PlayoffChoice, DatingProfile } from './types';

export const generateAvatar = (name: string) => `https://api.dicebear.com/8.x/adventurer/svg?seed=${encodeURIComponent(name)}`;

export const TEAMS: AllTeams = {
    "ATL": { name: "Atlanta Hawks", conference: "East", division: "Southeast", coach: { name: "Quin Snyder", personality: "tactical_genius", avatar: generateAvatar("Quin Snyder") }, logo: "https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg", primaryColor: "#E03A3E", secondaryColor: "#C1D32F", roster: [{ name: "Trae Young", position: Position.PG, overall: 89, personality: 'star_player' }, { name: "Dejounte Murray", position: Position.SG, overall: 84, personality: 'role_player' }, { name: "Jalen Johnson", position: Position.PF, overall: 80, personality: 'young_prospect' }, { name: "Clint Capela", position: Position.C, overall: 82, personality: 'defensive_anchor' }] },
    "BOS": { name: "Boston Celtics", conference: "East", division: "Atlantic", coach: { name: "Joe Mazzulla", personality: "tactical_genius", avatar: generateAvatar("Joe Mazzulla") }, logo: "https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg", primaryColor: "#007A33", secondaryColor: "#BA9653", roster: [{ name: "Jayson Tatum", position: Position.SF, overall: 93, personality: 'star_player' }, { name: "Jaylen Brown", position: Position.SG, overall: 90, personality: 'star_player' }, { name: "Jrue Holiday", position: Position.PG, overall: 85, personality: 'veteran_leader' }, { name: "Kristaps Porzingis", position: Position.C, overall: 86, personality: 'role_player' }] },
    "BKN": { name: "Brooklyn Nets", conference: "East", division: "Atlantic", coach: { name: "Jordi Fernández", personality: "players_coach", avatar: generateAvatar("Jordi Fernández") }, logo: "https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg", primaryColor: "#000000", secondaryColor: "#FFFFFF", roster: [{ name: "Mikal Bridges", position: Position.SF, overall: 84, personality: 'star_player' }, { name: "Cam Thomas", position: Position.SG, overall: 81, personality: 'role_player' }, { name: "Nic Claxton", position: Position.C, overall: 82, personality: 'defensive_anchor' }, { name: "Ben Simmons", position: Position.PG, overall: 79, personality: 'mercenary' }] },
    "CHA": { name: "Charlotte Hornets", conference: "East", division: "Southeast", coach: { name: "Charles Lee", personality: "motivational_leader", avatar: generateAvatar("Charles Lee") }, logo: "https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg", primaryColor: "#1D1160", secondaryColor: "#00788C", roster: [{ name: "LaMelo Ball", position: Position.PG, overall: 86, personality: 'star_player' }, { name: "Brandon Miller", position: Position.SF, overall: 82, personality: 'young_prospect' }, { name: "Mark Williams", position: Position.C, overall: 80, personality: 'defensive_anchor' }, { name: "Miles Bridges", position: Position.SF, overall: 81, personality: 'role_player' }] },
    "CHI": { name: "Chicago Bulls", conference: "East", division: "Central", coach: { name: "Billy Donovan", personality: "players_coach", avatar: generateAvatar("Billy Donovan") }, logo: "https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg", primaryColor: "#CE1141", secondaryColor: "#000000", roster: [{ name: "Zach LaVine", position: Position.SG, overall: 85, personality: 'star_player' }, { name: "Nikola Vucevic", position: Position.C, overall: 84, personality: 'veteran_leader' }, { name: "Josh Giddey", position: Position.PG, overall: 83, personality: 'young_prospect' }, { name: "Coby White", position: Position.SG, overall: 81, personality: 'role_player' }] },
    "CLE": { name: "Cleveland Cavaliers", conference: "East", division: "Central", coach: { name: "Kenny Atkinson", personality: "tactical_genius", avatar: generateAvatar("Kenny Atkinson") }, logo: "https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg", primaryColor: "#860038", secondaryColor: "#041E42", roster: [{ name: "Donovan Mitchell", position: Position.SG, overall: 90, personality: 'star_player' }, { name: "Darius Garland", position: Position.PG, overall: 86, personality: 'role_player' }, { name: "Evan Mobley", position: Position.PF, overall: 85, personality: 'young_prospect' }, { name: "Jarrett Allen", position: Position.C, overall: 85, personality: 'defensive_anchor' }] },
    "DAL": { name: "Dallas Mavericks", conference: "West", division: "Southwest", coach: { name: "Jason Kidd", personality: "players_coach", avatar: generateAvatar("Jason Kidd") }, logo: "https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg", primaryColor: "#00538C", secondaryColor: "#B8C4CA", roster: [{ name: "Luka Doncic", position: Position.PG, overall: 96, personality: 'star_player' }, { name: "Kyrie Irving", position: Position.SG, overall: 91, personality: 'star_player' }, { name: "Klay Thompson", position: Position.SG, overall: 83, personality: 'veteran_leader' }, { name: "Daniel Gafford", position: Position.C, overall: 81, personality: 'role_player' }] },
    "DEN": { name: "Denver Nuggets", conference: "West", division: "Northwest", coach: { name: "Michael Malone", personality: "motivational_leader", avatar: generateAvatar("Michael Malone") }, logo: "https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg", primaryColor: "#0E2240", secondaryColor: "#FEC524", roster: [{ name: "Nikola Jokic", position: Position.C, overall: 97, personality: 'star_player' }, { name: "Jamal Murray", position: Position.PG, overall: 86, personality: 'role_player' }, { name: "Michael Porter Jr.", position: Position.SF, overall: 84, personality: 'role_player' }, { name: "Aaron Gordon", position: Position.PF, overall: 82, personality: 'defensive_anchor' }] },
    "DET": { name: "Detroit Pistons", conference: "East", division: "Central", coach: { name: "Monty Williams", personality: "players_coach", avatar: generateAvatar("Monty Williams") }, logo: "https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg", primaryColor: "#C8102E", secondaryColor: "#006BB6", roster: [{ name: "Cade Cunningham", position: Position.PG, overall: 85, personality: 'star_player' }, { name: "Jaden Ivey", position: Position.SG, overall: 80, personality: 'young_prospect' }, { name: "Jalen Duren", position: Position.C, overall: 80, personality: 'young_prospect' }, { name: "Ausar Thompson", position: Position.SF, overall: 79, personality: 'defensive_anchor' }] },
    "GSW": { name: "Golden State Warriors", conference: "West", division: "Pacific", coach: { name: "Steve Kerr", personality: "players_coach", avatar: generateAvatar("Steve Kerr") }, logo: "https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg", primaryColor: "#006BB6", secondaryColor: "#FDB927", roster: [{ name: "Stephen Curry", position: Position.PG, overall: 96, personality: 'star_player' }, { name: "Draymond Green", position: Position.PF, overall: 83, personality: 'veteran_leader' }, { name: "Jonathan Kuminga", position: Position.PF, overall: 83, personality: 'young_prospect' }, { name: "Andrew Wiggins", position: Position.SF, overall: 82, personality: 'role_player' }] },
    "HOU": { name: "Houston Rockets", conference: "West", division: "Southwest", coach: { name: "Ime Udoka", personality: "motivational_leader", avatar: generateAvatar("Ime Udoka") }, logo: "https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg", primaryColor: "#CE1141", secondaryColor: "#000000", roster: [{ name: "Alperen Sengun", position: Position.C, overall: 85, personality: 'star_player' }, { name: "Fred VanVleet", position: Position.PG, overall: 84, personality: 'veteran_leader' }, { name: "Jalen Green", position: Position.SG, overall: 82, personality: 'young_prospect' }, { name: "Jabari Smith Jr.", position: Position.PF, overall: 80, personality: 'young_prospect' }] },
    "IND": { name: "Indiana Pacers", conference: "East", division: "Central", coach: { name: "Rick Carlisle", personality: "tactical_genius", avatar: generateAvatar("Rick Carlisle") }, logo: "https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg", primaryColor: "#002D62", secondaryColor: "#FDBB30", roster: [{ name: "Tyrese Haliburton", position: Position.PG, overall: 89, personality: 'star_player' }, { name: "Pascal Siakam", position: Position.PF, overall: 86, personality: 'role_player' }, { name: "Myles Turner", position: Position.C, overall: 83, personality: 'defensive_anchor' }, { name: "Bennedict Mathurin", position: Position.SG, overall: 82, personality: 'young_prospect' }] },
    "LAC": { name: "LA Clippers", conference: "West", division: "Pacific", coach: { name: "Tyronn Lue", personality: "players_coach", avatar: generateAvatar("Tyronn Lue") }, logo: "https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg", primaryColor: "#C8102E", secondaryColor: "#1D428A", roster: [{ name: "Kawhi Leonard", position: Position.SF, overall: 92, personality: 'star_player' }, { name: "James Harden", position: Position.PG, overall: 87, personality: 'mercenary' }, { name: "Ivica Zubac", position: Position.C, overall: 82, personality: 'role_player' }, { name: "Norman Powell", position: Position.SG, overall: 81, personality: 'role_player' }] },
    "LAL": { name: "Los Angeles Lakers", conference: "West", division: "Pacific", coach: { name: "JJ Redick", personality: "tactical_genius", avatar: generateAvatar("JJ Redick") }, logo: "https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg", primaryColor: "#552583", secondaryColor: "#FDB927", roster: [{ name: "LeBron James", position: Position.SF, overall: 95, personality: 'veteran_leader' }, { name: "Anthony Davis", position: Position.PF, overall: 93, personality: 'star_player' }, { name: "Austin Reaves", position: Position.SG, overall: 83, personality: 'role_player' }, { name: "D'Angelo Russell", position: Position.PG, overall: 81, personality: 'mercenary' }] },
    "MEM": { name: "Memphis Grizzlies", conference: "West", division: "Southwest", coach: { name: "Taylor Jenkins", personality: "players_coach", avatar: generateAvatar("Taylor Jenkins") }, logo: "https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg", primaryColor: "#5D76A9", secondaryColor: "#12173F", roster: [{ name: "Ja Morant", position: Position.PG, overall: 91, personality: 'star_player' }, { name: "Jaren Jackson Jr.", position: Position.PF, overall: 87, personality: 'defensive_anchor' }, { name: "Desmond Bane", position: Position.SG, overall: 86, personality: 'role_player' }, { name: "Marcus Smart", position: Position.SG, overall: 82, personality: 'veteran_leader' }] },
    "MIA": { name: "Miami Heat", conference: "East", division: "Southeast", coach: { name: "Erik Spoelstra", personality: "tactical_genius", avatar: generateAvatar("Erik Spoelstra") }, logo: "https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg", primaryColor: "#98002E", secondaryColor: "#F9A01B", roster: [{ name: "Jimmy Butler", position: Position.SF, overall: 90, personality: 'veteran_leader' }, { name: "Bam Adebayo", position: Position.C, overall: 88, personality: 'defensive_anchor' }, { name: "Tyler Herro", position: Position.SG, overall: 84, personality: 'role_player' }, { name: "Terry Rozier", position: Position.PG, overall: 83, personality: 'role_player' }] },
    "MIL": { name: "Milwaukee Bucks", conference: "East", division: "Central", coach: { name: "Doc Rivers", personality: "players_coach", avatar: generateAvatar("Doc Rivers") }, logo: "https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg", primaryColor: "#00471B", secondaryColor: "#EEE1C6", roster: [{ name: "Giannis Antetokounmpo", position: Position.PF, overall: 97, personality: 'star_player' }, { name: "Damian Lillard", position: Position.PG, overall: 89, personality: 'star_player' }, { name: "Khris Middleton", position: Position.SF, overall: 85, personality: 'role_player' }, { name: "Brook Lopez", position: Position.C, overall: 83, personality: 'veteran_leader' }] },
    "MIN": { name: "Minnesota Timberwolves", conference: "West", division: "Northwest", coach: { name: "Chris Finch", personality: "tactical_genius", avatar: generateAvatar("Chris Finch") }, logo: "https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg", primaryColor: "#0C2340", secondaryColor: "#236192", roster: [{ name: "Anthony Edwards", position: Position.SG, overall: 90, personality: 'star_player' }, { name: "Karl-Anthony Towns", position: Position.PF, overall: 88, personality: 'star_player' }, { name: "Rudy Gobert", position: Position.C, overall: 88, personality: 'defensive_anchor' }, { name: "Jaden McDaniels", position: Position.SF, overall: 81, personality: 'defensive_anchor' }] },
    "NOP": { name: "New Orleans Pelicans", conference: "West", division: "Southwest", coach: { name: "Willie Green", personality: "players_coach", avatar: generateAvatar("Willie Green") }, logo: "https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg", primaryColor: "#0C2340", secondaryColor: "#C8102E", roster: [{ name: "Zion Williamson", position: Position.PF, overall: 89, personality: 'star_player' }, { name: "Brandon Ingram", position: Position.SF, overall: 85, personality: 'role_player' }, { name: "Dejounte Murray", position: Position.SG, overall: 85, personality: 'role_player' }, { name: "CJ McCollum", position: Position.PG, overall: 84, personality: 'veteran_leader' }] },
    "NYK": { name: "New York Knicks", conference: "East", division: "Atlantic", coach: { name: "Tom Thibodeau", personality: "old_school_disciplinarian", avatar: generateAvatar("Tom Thibodeau") }, logo: "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg", primaryColor: "#006BB6", secondaryColor: "#F58426", roster: [{ name: "Jalen Brunson", position: Position.PG, overall: 91, personality: 'star_player' }, { name: "Karl-Anthony Towns", position: Position.C, overall: 88, personality: 'star_player' }, { name: "Julius Randle", position: Position.PF, overall: 85, personality: 'role_player' }, { name: "OG Anunoby", position: Position.SF, overall: 84, personality: 'defensive_anchor' }] },
    "OKC": { name: "Oklahoma City Thunder", conference: "West", division: "Northwest", coach: { name: "Mark Daigneault", personality: "tactical_genius", avatar: generateAvatar("Mark Daigneault") }, logo: "https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg", primaryColor: "#007AC1", secondaryColor: "#EF3B24", roster: [{ name: "Shai Gilgeous-Alexander", position: Position.PG, overall: 94, personality: 'star_player' }, { name: "Chet Holmgren", position: Position.PF, overall: 86, personality: 'young_prospect' }, { name: "Jalen Williams", position: Position.SF, overall: 85, personality: 'young_prospect' }, { name: "Josh Giddey", position: Position.SF, overall: 82, personality: 'role_player' }] },
    "ORL": { name: "Orlando Magic", conference: "East", division: "Southeast", coach: { name: "Jamahl Mosley", personality: "motivational_leader", avatar: generateAvatar("Jamahl Mosley") }, logo: "https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg", primaryColor: "#0077C0", secondaryColor: "#C4CED3", roster: [{ name: "Paolo Banchero", position: Position.PF, overall: 88, personality: 'star_player' }, { name: "Franz Wagner", position: Position.SF, overall: 87, personality: 'young_prospect' }, { name: "Jalen Suggs", position: Position.PG, overall: 82, personality: 'defensive_anchor' }, { name: "Wendell Carter Jr.", position: Position.C, overall: 82, personality: 'role_player' }] },
    "PHI": { name: "Philadelphia 76ers", conference: "East", division: "Atlantic", coach: { name: "Nick Nurse", personality: "tactical_genius", avatar: generateAvatar("Nick Nurse") }, logo: "https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg", primaryColor: "#006BB6", secondaryColor: "#ED174C", roster: [{ name: "Joel Embiid", position: Position.C, overall: 96, personality: 'star_player' }, { name: "Tyrese Maxey", position: Position.SG, overall: 89, personality: 'young_prospect' }, { name: "Paul George", position: Position.SF, overall: 88, personality: 'veteran_leader' }, { name: "Tobias Harris", position: Position.PF, overall: 82, personality: 'role_player' }] },
    "PHX": { name: "Phoenix Suns", conference: "West", division: "Pacific", coach: { name: "Mike Budenholzer", personality: "tactical_genius", avatar: generateAvatar("Mike Budenholzer") }, logo: "https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg", primaryColor: "#1D1160", secondaryColor: "#E56020", roster: [{ name: "Kevin Durant", position: Position.SF, overall: 93, personality: 'star_player' }, { name: "Devin Booker", position: Position.SG, overall: 91, personality: 'star_player' }, { name: "Bradley Beal", position: Position.SG, overall: 86, personality: 'role_player' }, { name: "Jusuf Nurkic", position: Position.C, overall: 81, personality: 'role_player' }] },
    "POR": { name: "Portland Trail Blazers", conference: "West", division: "Northwest", coach: { name: "Chauncey Billups", personality: "players_coach", avatar: generateAvatar("Chauncey Billups") }, logo: "https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg", primaryColor: "#E03A3E", secondaryColor: "#000000", roster: [{ name: "Deandre Ayton", position: Position.C, overall: 84, personality: 'role_player' }, { name: "Anfernee Simons", position: Position.SG, overall: 84, personality: 'young_prospect' }, { name: "Jerami Grant", position: Position.PF, overall: 82, personality: 'mercenary' }, { name: "Scoot Henderson", position: Position.PG, overall: 81, personality: 'young_prospect' }] },
    "SAC": { name: "Sacramento Kings", conference: "West", division: "Pacific", coach: { name: "Mike Brown", personality: "motivational_leader", avatar: generateAvatar("Mike Brown") }, logo: "https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg", primaryColor: "#5A2D81", secondaryColor: "#63727A", roster: [{ name: "De'Aaron Fox", position: Position.PG, overall: 90, personality: 'star_player' }, { name: "Domantas Sabonis", position: Position.C, overall: 88, personality: 'star_player' }, { name: "DeMar DeRozan", position: Position.SF, overall: 87, personality: 'veteran_leader' }, { name: "Keegan Murray", position: Position.PF, overall: 82, personality: 'young_prospect' }] },
    "SAS": { name: "San Antonio Spurs", conference: "West", division: "Southwest", coach: { name: "Gregg Popovich", personality: "old_school_disciplinarian", avatar: generateAvatar("Gregg Popovich") }, logo: "https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg", primaryColor: "#C4CED3", secondaryColor: "#000000", roster: [{ name: "Victor Wembanyama", position: Position.PF, overall: 90, personality: 'young_prospect' }, { name: "Chris Paul", position: Position.PG, overall: 85, personality: 'veteran_leader' }, { name: "Devin Vassell", position: Position.SG, overall: 83, personality: 'role_player' }, { name: "Keldon Johnson", position: Position.SF, overall: 82, personality: 'role_player' }] },
    "TOR": { name: "Toronto Raptors", conference: "East", division: "Atlantic", coach: { name: "Darko Rajaković", personality: "players_coach", avatar: generateAvatar("Darko Rajaković") }, logo: "https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg", primaryColor: "#CE1141", secondaryColor: "#000000", roster: [{ name: "Scottie Barnes", position: Position.PF, overall: 88, personality: 'star_player' }, { name: "Immanuel Quickley", position: Position.PG, overall: 84, personality: 'role_player' }, { name: "RJ Barrett", position: Position.SF, overall: 83, personality: 'role_player' }, { name: "Jakob Poeltl", position: Position.C, overall: 82, personality: 'defensive_anchor' }] },
    "UTA": { name: "Utah Jazz", conference: "West", division: "Northwest", coach: { name: "Will Hardy", personality: "tactical_genius", avatar: generateAvatar("Will Hardy") }, logo: "https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg", primaryColor: "#002B5C", secondaryColor: "#F9A01B", roster: [{ name: "Lauri Markkanen", position: Position.PF, overall: 87, personality: 'star_player' }, { name: "Collin Sexton", position: Position.SG, overall: 81, personality: 'role_player' }, { name: "John Collins", position: Position.PF, overall: 81, personality: 'role_player' }, { name: "Walker Kessler", position: Position.C, overall: 81, personality: 'defensive_anchor' }] },
    "WAS": { name: "Washington Wizards", conference: "East", division: "Southeast", coach: { name: "Brian Keefe", personality: "motivational_leader", avatar: generateAvatar("Brian Keefe") }, logo: "https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg", primaryColor: "#002B5C", secondaryColor: "#E31837", roster: [{ name: "Kyle Kuzma", position: Position.PF, overall: 83, personality: 'mercenary' }, { name: "Jordan Poole", position: Position.SG, overall: 82, personality: 'locker_room_prankster' }, { name: "Jonas Valančiūnas", position: Position.C, overall: 82, personality: 'veteran_leader' }, { name: "Deni Avdija", position: Position.SF, overall: 80, personality: 'role_player' }] },
};

export const ALL_TROPHIES: Trophy[] = [
    { id: "mvp" }, { id: "fmvp" }, { id: "scoring-champ" }, { id: "all-star" }, 
    { id: "all-nba" }, { id: "rookie-year" }, { id: "dpoy" }, { id: "sixth-man" }, 
    { id: "most-improved" },
];

export const ALL_ACHIEVEMENTS: Achievement[] = [
    { id: "first-game" }, { id: "first-points" }, { id: "double-double" }, 
    { id: "30-points" }, { id: "drafted" }, { id: "lottery-pick" }, 
    { id: "playoff-berth" }, { id: "playoff-win" }, { id: "series-win" }, 
    { id: "conference-finals" }, { id: "nba-finals" }, { id: "champion" }, 
    { id: "triple-double" }, { id: "50-point-game" }, { id: "jersey-retired" }, 
    { id: "hall-of-fame" }, { id: "legend" },
];

export const ATTRIBUTES = [
    { id: "shooting" }, { id: "midrange" }, { id: "threepoint" }, 
    { id: "finishing" }, { id: "defense" }, { id: "perimeter_d" }, 
    { id: "athleticism" }, { id: "speed" }, { id: "playmaking" }, 
    { id: "ball_handle" }, { id: "rebounding" }, { id: "strength" },
];

export const TOTAL_ATTRIBUTE_POINTS = 110;
export const MIN_ATTRIBUTE_POINTS = 5;
export const MAX_ATTRIBUTE_POINTS = 20;
export const CLUTCH_TRAIT_COST = 5;

export const QUICK_BUILDS: { [key: string]: { stats: Partial<PlayerStats> } } = {
    shooter: { stats: { shooting: 18, midrange: 18, threepoint: 20, finishing: 11, defense: 7, perimeter_d: 8, athleticism: 10, speed: 11, playmaking: 15, ball_handle: 17, rebounding: 8, strength: 7 } },
    slasher: { stats: { shooting: 10, midrange: 15, threepoint: 10, finishing: 20, defense: 9, perimeter_d: 8, athleticism: 18, speed: 20, playmaking: 14, ball_handle: 19, rebounding: 7, strength: 10 } },
    lockdown_defender: { stats: { shooting: 8, midrange: 9, threepoint: 8, finishing: 12, defense: 20, perimeter_d: 20, athleticism: 15, speed: 15, playmaking: 10, ball_handle: 9, rebounding: 14, strength: 15 } },
    playmaker: { stats: { shooting: 13, midrange: 13, threepoint: 12, finishing: 12, defense: 8, perimeter_d: 10, athleticism: 12, speed: 18, playmaking: 20, ball_handle: 20, rebounding: 6, strength: 6 } },
    glass_cleaner: { stats: { shooting: 7, midrange: 8, threepoint: 6, finishing: 15, defense: 18, perimeter_d: 8, athleticism: 13, speed: 8, playmaking: 7, ball_handle: 6, rebounding: 20, strength: 19 } },
    two_way: { stats: { shooting: 13, midrange: 14, threepoint: 13, finishing: 14, defense: 15, perimeter_d: 15, athleticism: 12, speed: 12, playmaking: 13, ball_handle: 12, rebounding: 12, strength: 15 } },
    stretch_big: { stats: { shooting: 15, midrange: 17, threepoint: 16, finishing: 14, defense: 12, perimeter_d: 8, athleticism: 10, speed: 9, playmaking: 9, ball_handle: 8, rebounding: 19, strength: 18 } },
    athletic_freak: { stats: { shooting: 11, midrange: 12, threepoint: 8, finishing: 19, defense: 13, perimeter_d: 11, athleticism: 20, speed: 20, playmaking: 10, ball_handle: 11, rebounding: 12, strength: 18 } },
    all_around: { stats: { shooting: 14, midrange: 14, threepoint: 14, finishing: 14, defense: 14, perimeter_d: 14, athleticism: 14, speed: 14, playmaking: 14, ball_handle: 14, rebounding: 14, strength: 14 } },
    post_scorer: { stats: { shooting: 8, midrange: 18, threepoint: 6, finishing: 18, defense: 12, perimeter_d: 6, athleticism: 13, speed: 6, playmaking: 10, ball_handle: 11, rebounding: 18, strength: 19 } },
};

export const DATING_PROFILES: DatingProfile[] = [
    { id: 'dp_zendaya', name: 'Zendaya', occupation: 'Actress & Fashion Icon', bio: 'Just a girl from Oakland figuring it out. My work keeps me busy, but I make time for what\'s important. Looking for someone genuine who doesn\'t take themselves too seriously.', avatar: generateAvatar('Zendaya'), personality: 'Down-to-earth, witty, and fiercely loyal. She is ambitious and hardworking but values her privacy and authentic connections.' },
    { id: 'dp_sydney', name: 'Sydney Sweeney', occupation: 'Actress', bio: 'Probably fixing up a vintage car or on a movie set. Love spontaneous adventures. Can you keep up?', avatar: generateAvatar('Sydney Sweeney'), personality: 'Bubbly and adventurous with a surprising tomboy streak. She\'s confident and playful, but also has a thoughtful, introspective side.' },
    { id: 'dp_dua', name: 'Dua Lipa', occupation: 'Pop Star', bio: 'Traveling the world, one stage at a time. My life\'s a little crazy, but I promise it\'s never boring. Let\'s make some memories.', avatar: generateAvatar('Dua Lipa'), personality: 'Charismatic, confident, and a true globetrotter. She has a magnetic energy and is always looking for the next fun experience.' },
    { id: 'dp_hailey', name: 'Hailey Bieber', occupation: 'Model & Entrepreneur', bio: 'My life is a balance of runways, business meetings, and quiet nights in. Looking for a partner who appreciates both sides.', avatar: generateAvatar('Hailey Bieber'), personality: 'Chic, business-savvy, and composed. She has a calm and collected demeanor but is very driven and protective of her inner circle.' },
    { id: 'dp_olivia', name: 'Olivia Rodrigo', occupation: 'Singer-Songwriter', bio: 'I write songs about my feelings, so be nice to me! Just kidding... mostly. Let\'s get boba.', avatar: generateAvatar('Olivia Rodrigo'), personality: 'Artistic, emotionally intelligent, and a bit of an old soul. She is sweet and relatable, with a sharp wit and a flair for the dramatic.' },
    { id: 'dp_ariana', name: 'Ariana Grande', occupation: 'Singer & Actress', bio: 'Just trying to make the world a little brighter, one song at a time. Love my dogs, vegan food, and a good laugh.', avatar: generateAvatar('Ariana Grande'), personality: 'Sweet and bubbly, but also a savvy and powerful businesswoman. She is kind to her fans but protective of her personal life.' },
    { id: 'dp_jenna', name: 'Jenna Ortega', occupation: 'Actress', bio: 'Into all things dark and mysterious. Probably listening to goth rock or reading a classic novel. Not your typical LA girl.', avatar: generateAvatar('Jenna Ortega'), personality: 'Has a dry, sarcastic wit and a unique, slightly dark sense of humor. She is intelligent, introspective, and not easily impressed.' },
    { id: 'dp_ana', name: 'Ana de Armas', occupation: 'Actress', bio: 'A Cuban girl living the Hollywood dream. Love to dance, travel, and spend time with my dog, Elvis. Looking for an authentic connection.', avatar: generateAvatar('Ana de Armas'), personality: 'Charming, warm, and charismatic with a magnetic screen presence. She is passionate and values genuine relationships over fleeting fame.' },
    { id: 'dp_sabrina', name: 'Sabrina Carpenter', occupation: 'Singer & Actress', bio: 'Making music and making trouble. If you can handle my tour schedule and my sense of humor, we might get along.', avatar: generateAvatar('Sabrina Carpenter'), personality: 'Confident, playful, and quick-witted. She has a sharp sense of humor and a charismatic stage presence that translates to her real life.' }
];

export const PLAYOFF_STRATEGIES: PlayoffChoice[] = [
    // --- Offensive Strategies ---
    { id: 'iso_hero_ball', category: 'offensive', risk: 'high', primaryStat: 'finishing', secondaryStat: 'ball_handle', personalityTrait: 'confident', minStats: { finishing: 16, ball_handle: 16 },
        successEffects: { playerPerformanceBoost: { points: 25 }, teamOffenseBoost: -5 },
        failureEffects: { playerPerformanceBoost: { points: -15 }, teamOffenseBoost: -10 } },
    { id: 'three_point_barrage', category: 'offensive', risk: 'high', primaryStat: 'threepoint', secondaryStat: 'shooting', minStats: { threepoint: 17, shooting: 15 },
        successEffects: { teamOffenseBoost: 10 },
        failureEffects: { teamOffenseBoost: -8, teamDefenseBoost: -2 } },
    { id: 'fastbreak_frenzy', category: 'offensive', risk: 'medium', primaryStat: 'speed', secondaryStat: 'ball_handle', minStats: { speed: 16 },
        successEffects: { teamOffenseBoost: 7 },
        failureEffects: { teamDefenseBoost: -5 } },
    { id: 'pick_and_roll_mastery', category: 'offensive', risk: 'medium', primaryStat: 'playmaking', secondaryStat: 'midrange', minStats: { playmaking: 15, ball_handle: 14 },
        successEffects: { playerPerformanceBoost: { assists: 20 }, teamOffenseBoost: 5 },
        failureEffects: { teamOffenseBoost: -5 } },
    { id: 'attack_the_paint', category: 'offensive', risk: 'medium', primaryStat: 'finishing', secondaryStat: 'strength', minStats: { finishing: 15 },
        successEffects: { playerPerformanceBoost: { points: 10 }, teamOffenseBoost: 4 },
        failureEffects: { teamOffenseBoost: -4 } },
    { id: 'mid_range_clinic', category: 'offensive', risk: 'low', primaryStat: 'midrange', secondaryStat: 'shooting', minStats: { midrange: 16 },
        successEffects: { playerPerformanceBoost: { points: 15 } },
        failureEffects: { playerPerformanceBoost: { points: -5 }, teamOffenseBoost: -3 } },
    { id: 'patient_offense', category: 'offensive', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'ball_handle',
        successEffects: { teamOffenseBoost: 3, teamDefenseBoost: 2 },
        failureEffects: { teamOffenseBoost: -2 } },
    { id: 'post_up_bully', category: 'offensive', risk: 'medium', primaryStat: 'strength', secondaryStat: 'finishing', minStats: { strength: 16, finishing: 14 },
        successEffects: { playerPerformanceBoost: { points: 10, rebounds: 10 } },
        failureEffects: { teamOffenseBoost: -6 } },
    { id: 'unleash_creative_playmaking', category: 'offensive', risk: 'high', primaryStat: 'ball_handle', secondaryStat: 'playmaking', personalityTrait: 'maverick', minStats: { playmaking: 17, ball_handle: 17 },
        successEffects: { playerPerformanceBoost: { assists: 30 }, teamOffenseBoost: 8 },
        failureEffects: { teamOffenseBoost: -8, teamDefenseBoost: -3 } },

    // --- Defensive Strategies ---
    { id: 'full_court_press', category: 'defensive', risk: 'high', primaryStat: 'perimeter_d', secondaryStat: 'speed', minStats: { perimeter_d: 15, speed: 15 },
        successEffects: { opponentOffenseNerf: 10, teamDefenseBoost: 5 },
        failureEffects: { teamDefenseBoost: -10 } },
    { id: 'pack_the_paint', category: 'defensive', risk: 'medium', primaryStat: 'defense', secondaryStat: 'strength', minStats: { defense: 15 },
        successEffects: { teamDefenseBoost: 8 },
        failureEffects: { opponentDefenseNerf: -8 } },
    { id: 'run_shooters_off_line', category: 'defensive', risk: 'medium', primaryStat: 'perimeter_d', secondaryStat: 'athleticism', minStats: { perimeter_d: 16 },
        successEffects: { teamDefenseBoost: 6, opponentOffenseNerf: 4 },
        failureEffects: { teamDefenseBoost: -6 } },
    { id: 'force_tough_midrange', category: 'defensive', risk: 'low', primaryStat: 'defense', secondaryStat: 'perimeter_d',
        successEffects: { teamDefenseBoost: 4 },
        failureEffects: { opponentDefenseNerf: -2 } },
    { id: 'lock_down_star_player', category: 'defensive', risk: 'high', primaryStat: 'perimeter_d', secondaryStat: 'defense', personalityTrait: 'aggressive', minStats: { perimeter_d: 17, defense: 17 },
        successEffects: { opponentOffenseNerf: 12 },
        failureEffects: { teamDefenseBoost: -8 } },
    { id: 'switch_everything', category: 'defensive', risk: 'medium', primaryStat: 'athleticism', secondaryStat: 'defense', minStats: { athleticism: 14, speed: 14, defense: 14 },
        successEffects: { teamDefenseBoost: 5, opponentOffenseNerf: 3 },
        failureEffects: { teamDefenseBoost: -7 } },
    { id: 'trap_the_ball_handler', category: 'defensive', risk: 'high', primaryStat: 'speed', secondaryStat: 'perimeter_d', minStats: { speed: 16, perimeter_d: 14 },
        successEffects: { opponentOffenseNerf: 9 },
        failureEffects: { teamDefenseBoost: -9 } },
    { id: 'physical_defense', category: 'defensive', risk: 'medium', primaryStat: 'strength', secondaryStat: 'defense', personalityTrait: 'aggressive', minStats: { strength: 15 },
        successEffects: { teamDefenseBoost: 6, playerPerformanceBoost: { rebounds: 10 } },
        failureEffects: { teamDefenseBoost: -4 } },
    { id: 'secure_defensive_rebounds', category: 'defensive', risk: 'low', primaryStat: 'rebounding', secondaryStat: 'strength', minStats: { rebounding: 15 },
        successEffects: { playerPerformanceBoost: { rebounds: 20 }, teamDefenseBoost: 2 },
        failureEffects: { playerPerformanceBoost: { rebounds: -10 } } },
    { id: 'enforce_the_paint', category: 'defensive', risk: 'medium', primaryStat: 'defense', secondaryStat: 'strength', personalityTrait: 'aggressive', minStats: { defense: 16, strength: 14 },
        successEffects: { teamDefenseBoost: 7, opponentOffenseNerf: 3 },
        failureEffects: { teamDefenseBoost: -5 } },

    // --- Team Strategies ---
    { id: 'slow_the_pace', category: 'team', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'strength',
        successEffects: { teamDefenseBoost: 3, opponentOffenseNerf: 2 },
        failureEffects: { teamOffenseBoost: -3 } },
    { id: 'push_the_pace', category: 'team', risk: 'medium', primaryStat: 'speed', secondaryStat: 'athleticism', minStats: { speed: 15 },
        successEffects: { teamOffenseBoost: 6 },
        failureEffects: { teamDefenseBoost: -6 } },
    { id: 'veteran_leadership', category: 'team', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'shooting', personalityTrait: 'team_player',
        successEffects: { teamOffenseBoost: 2, teamDefenseBoost: 2 },
        failureEffects: { } },
    { id: 'small_ball_lineup', category: 'team', risk: 'high', primaryStat: 'speed', secondaryStat: 'threepoint', minStats: { speed: 14, threepoint: 13 },
        successEffects: { teamOffenseBoost: 9 },
        failureEffects: { teamDefenseBoost: -9 } },
    { id: 'big_ball_lineup', category: 'team', risk: 'high', primaryStat: 'strength', secondaryStat: 'rebounding', minStats: { strength: 15, rebounding: 15 },
        successEffects: { teamDefenseBoost: 9 },
        failureEffects: { teamOffenseBoost: -9 } },
    { id: 'focus_on_ball_movement', category: 'team', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'ball_handle', personalityTrait: 'team_player',
        successEffects: { teamOffenseBoost: 4, playerPerformanceBoost: { assists: 10 } },
        failureEffects: { teamOffenseBoost: -2 } },
    { id: 'crash_offensive_glass', category: 'team', risk: 'medium', primaryStat: 'rebounding', secondaryStat: 'athleticism', minStats: { rebounding: 16, athleticism: 14 },
        successEffects: { playerPerformanceBoost: { rebounds: 15 }, teamOffenseBoost: 3 },
        failureEffects: { teamDefenseBoost: -5 } },
    { id: 'coachs_pep_talk', category: 'team', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'shooting', personalityTrait: 'hardworking',
        successEffects: { teamOffenseBoost: 3, teamDefenseBoost: 1 },
        failureEffects: { } },
    { id: 'fan_favorite_play', category: 'team', risk: 'medium', primaryStat: 'athleticism', secondaryStat: 'finishing', personalityTrait: 'maverick', minStats: { athleticism: 17, finishing: 15 },
        successEffects: { teamOffenseBoost: 5, playerPerformanceBoost: { points: 5 } },
        failureEffects: { teamOffenseBoost: -4 } },
    { id: 'trash_talk_opponent', category: 'team', risk: 'high', primaryStat: 'playmaking', secondaryStat: 'strength', personalityTrait: 'confident',
        successEffects: { opponentOffenseNerf: 5, opponentDefenseNerf: 5 },
        failureEffects: { teamOffenseBoost: -5, teamDefenseBoost: -5 } },
    { id: 'study_film_and_exploit', category: 'team', risk: 'low', primaryStat: 'playmaking', secondaryStat: 'shooting', personalityTrait: 'hardworking',
        successEffects: { opponentDefenseNerf: 4, teamOffenseBoost: 2 },
        failureEffects: { } },
    { id: 'rally_the_team', category: 'team', risk: 'medium', primaryStat: 'playmaking', secondaryStat: 'ball_handle', personalityTrait: 'team_player',
        successEffects: { teamOffenseBoost: 3, teamDefenseBoost: 3 },
        failureEffects: { } }
];